Repository Arggusx/ProjetoTopDown, pull requests merged in 2025-06, with the labels that each got.

#9 Correção de bugs e balanceamento.
  Assets/Prefabs/Trees/Tree.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene/NavMesh-NavMesh.asset
  Assets/Scripts/Dialogue/DialogueControl.cs
  Assets/Scripts/Dialogue/NPC_1.asset
  Assets/Scripts/Dialogue/Player.prefab
  Assets/Scripts/Dialogue/Player.prefab.meta
  Assets/Scripts/Enemy/Skeleton.cs
  Assets/Scripts/Farm/SlotFarm.cs
  Assets/Scripts/NPC/NPC_Dialogue.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/PlayerAnim.cs
  Assets/Sprites/SUNNYSIDE_WORLD_ASSETS_V0.2/TILESET/SunnysideWorld_Tileset_V0.1.png.meta
  Assets/UI/Dialogue/Captura de tela de 2025-06-02 18-06-10.png
  Assets/UI/Dialogue/Captura de tela de 2025-06-02 18-06-10.png.meta
Labels: bug

#11 Corrigue bugs de diálogo.
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Dialogue/DialogueControl.cs
  Assets/Scripts/Dialogue/DialogueSttings.meta
  Assets/Scripts/Dialogue/DialogueSttings/NPC_1.asset
  Assets/Scripts/Dialogue/DialogueSttings/NPC_1.asset.meta
  Assets/Scripts/Dialogue/DialogueSttings/NPC_3.asset
  Assets/Scripts/Dialogue/DialogueSttings/NPC_3.asset.meta
  Assets/Scripts/Dialogue/DialogueSttings/NPC_4.asset
  Assets/Scripts/Dialogue/DialogueSttings/NPC_4.asset.meta
  Assets/Scripts/Dialogue/DialogueSttings/NPC_5.asset
  Assets/Scripts/Dialogue/DialogueSttings/NPC_5.asset.meta
  Assets/Scripts/Dialogue/NPC_3.prefab
  Assets/Scripts/Dialogue/NPC_3.prefab.meta
  Assets/Scripts/Dialogue/NPC_4.prefab
  Assets/Scripts/Dialogue/NPC_4.prefab.meta
  Assets/Scripts/Dialogue/NPC_5.prefab
  Assets/Scripts/Dialogue/NPC_5.prefab.meta
  Assets/Scripts/Enemy/AnimationControll.cs
Labels: bug

#16 player: Muda os atalhos de teclado para ferramentas.
  Assets/Scripts/Player.cs
Labels: enhancement

#23 Update README.md
  README.md
Labels: documentation
